import Head from 'next/head'
import Image from 'next/image'
import Hexagon from '../components/icons/hexagon'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className='bg-white overflow-x-hiddden'>
        <canvas className="absolute origin-bottom-left -rotate-12 w-[9999px] overflow-hidden h-[80vh] -mt-4 bg-blue-dark"></canvas>
        <section className="z-10 relative pt-[30vh] max-w-wrapper mx-auto px-4 flex justify-between">
          <h1 className="text-white w-[40%]">Doktor Eriksen, MD.</h1>
          <figure className='-mt-8'>
            <Image src="/portrett.jpg" width={350} height={450}  />
          </figure>
        </section>
      </header>

      <main className='bg-white'>
        <section className='max-w-wrapper mx-auto px-4 py-16'>
          <h2 className='text-blue-dark'>Proficiencies</h2>
          
          <ul className='grid grid-cols-3 gap-4 mt-8'>
            <li className='relative'>
              <Hexagon />
              <figure className="absolute top-0 left-0 w-full h-full flex justify-center items-center">
                <Image src="/python.png" width={200} height={200} className='p-8' />
              </figure>
            </li>

            <li className='relative'>
              <Hexagon />
              <figure className="absolute top-0 left-0 w-full h-full flex justify-center items-center">
                <Image src="/julia.png" width={200} height={130} className='p-8' />
              </figure>
            </li>

            <li className='relative'>
              <Hexagon />
              <figure className="absolute top-0 left-0 w-full h-full flex justify-center items-center">
                <Image src="/haskell.png" width={150} height={150} className='p-8' />
              </figure>
            </li>

          </ul>
        </section>

      </main>

    </>
  )
}
