import Head from 'next/head'
import Header from '../components/header'
import Proficiencies from '../components/proficiencies'
import Repositories from '../components/repositories'
import GalleryComponent from "../components/gallery.component";

export default function Home({repos, preview}) {
  console.log(repos)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet" />        
      </Head>
      <Header />
      <main className='bg-white font-roboto-mono'>
        <Proficiencies />
        <Repositories repos={repos} />
        <GalleryComponent />
      </main>

    </>
  )
}


export async function getStaticProps({ preview = false }) {
  const reposResponse = await fetch('https://api.github.com/users/erikhys/repos')
  const repos = await reposResponse.json()
  return {
    props: { repos, preview },
  }
}